var testData = {
  lines: [{
    id: 'line1',
    name: '1号线',
    color: '#151965',
    width: 8,
    running: true,
    points: [
      [{
        x: 1920,
        y: 20
      }, {
        x: 1920,
        y: 2620
      }]
    ]
  }, {
    id: 'line1',
    name: '1号线支线',
    color: '#151965',
    width: 8,
    running: true,
    points: [
      [{
        x: 1920,
        y: 1780
      }, {
        x: 2000,
        y: 1780
      }, {
        x: 2000,
        y: 1860
      }]
    ]
  },  {
    id: 'line7',
    name: '7号线',
    color: '#4f98ca',
    width: 8,
    running: true,
    points: [
      [{
        x: 1920,
        y: 180
      }, {
        x: 1440,
        y: 180
      }, {
        x: 1400,
        y: 260
      }, {
        x: 1400,
        y: 900
      }, {
        x: 1440,
        y: 980
      }, {
        x: 1920,
        y: 980
      }, {
        x: 2400,
        y: 980
      }, {
        x: 2440,
        y: 900
      }, {
        x: 2440,
        y: 260
      }, {
        x: 2400,
        y: 180
      }, {
        x: 1920,
        y: 180
      }]
    ]
  },{
    id: 'line2',
    name: '2号线',
    color: '#eb8242',
    width: 8,
    running: true,
    points: [
      [{
        x: 900,
        y: 40
      }, {
        x: 960,
        y: 40
      }, {
        x: 1440,
        y: 180
      }, {
        x: 1860,
        y: 500
      },{
        x: 1920,
        y: 500
      }, {
        x: 2440,
        y: 900
      }, {
        x: 2520,
        y: 900
      }, {
        x: 2900,
        y: 1560
      }]
    ]
  }],
  stations: [
    //1号线
    {
      id: 'station1',
      name: '韦家碾',
      type: 1,
      x: 1920,
      y: 20,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station2',
      name: '升仙湖',
      type: 1,
      x: 1920,
      y: 100,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station3',
      name: '火车北站',
      type: 1,
      x: 1920,
      y: 180,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station4',
      name: '人民北路',
      type: 1,
      x: 1920,
      y: 260,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station5',
      name: '文殊院',
      type: 1,
      x: 1920,
      y: 340,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station6',
      name: '骡马市',
      type: 1,
      x: 1920,
      y: 420,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station7',
      name: '天府广场',
      type: 1,
      x: 1920,
      y: 500,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station8',
      name: '锦江宾馆',
      type: 1,
      x: 1920,
      y: 580,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station9',
      name: '华西坝',
      type: 1,
      x: 1920,
      y: 660,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station10',
      name: '省体育馆站',
      type: 1,
      x: 1920,
      y: 740,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station11',
      name: '倪家桥',
      type: 1,
      x: 1920,
      y: 820,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station12',
      name: '桐梓林',
      type: 1,
      x: 1920,
      y: 900,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station13',
      name: '火车南站',
      type: 1,
      x: 1920,
      y: 980,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station14',
      name: '高新',
      type: 1,
      x: 1920,
      y: 1060,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station15',
      name: '金融城',
      type: 1,
      x: 1920,
      y: 1140,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station16',
      name: '孵化园',
      type: 1,
      x: 1920,
      y: 1220,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station17',
      name: '锦城广场',
      type: 1,
      x: 1920,
      y: 1300,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station18',
      name: '世纪城',
      type: 1,
      x: 1920,
      y: 1380,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station19',
      name: '天府三街',
      type: 1,
      x: 1920,
      y: 1460,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station20',
      name: '天府五街',
      type: 1,
      x: 1920,
      y: 1540,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station21',
      name: '华府大道',
      type: 1,
      x: 1920,
      y: 1620,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station22',
      name: '四河',
      type: 1,
      x: 1920,
      y: 1700,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station23',
      name: '华阳',
      type: 1,
      x: 1920,
      y: 1780,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station24',
      name: '海昌路',
      type: 1,
      x: 1920,
      y: 1860,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station25',
      name: '广福',
      type: 1,
      x: 1920,
      y: 1940,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station26',
      name: '红石公园',
      type: 1,
      x: 1920,
      y: 2060,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station27',
      name: '麓湖',
      type: 1,
      x: 1920,
      y: 2140,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station28',
      name: '武汉路',
      type: 1,
      x: 1920,
      y: 2220,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station29',
      name: '天府公园',
      type: 1,
      x: 1920,
      y: 2300,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station30',
      name: '西博城',
      type: 1,
      x: 1920,
      y: 2380,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station31',
      name: '广州路',
      type: 1,
      x: 1920,
      y: 2460,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station32',
      name: '兴隆湖',
      type: 1,
      x: 1920,
      y: 2540,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station33',
      name: '科学城',
      type: 1,
      x: 1920,
      y: 2620,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station34',
      name: '广都',
      type: 1,
      x: 2000,
      y: 1780,
      status: 'normal',
      rotation: 0
    }, {
      id: 'station35',
      name: '五根松',
      type: 1,
      x: 2000,
      y: 1860,
      status: 'normal',
      rotation: 0
    }
  ]
}
